spring.application.name=search-service-comparison-utility
server.servlet.context-path=/
spring.mvc.servlet.path=/

search.index-name=alpha_search

BLUE_SEARCH_CLUSTER_URL=http://localhost:9400/
GREEN_SEARCH_CLUSTER_URL=http://localhost:9500/
